# Common LSP configurations

# NOTE: On all (or almost all) languages codebook is added for spell check

# TOML
# In the case of Artix Linux, the LSP is installed with a post hook
# For NixOS it is installed on the flake of the project
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true
language-servers = ["codebook"]

# Configuration for Markdown using Marksman and ltex-ls
[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls"]


# === === === === Languages that also are impacted by the Tailwind LSP === === === ===
[[language]]
name = "html"
language-servers = [{ name = "superhtml", except-features = ["format"] }, "vscode-html-language-server", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "php"
language-servers = ["phpactor", "tailwindcss-ls"]


# === === === === Configurations === === === ===

# YAML LSP Configurations
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

# LSP Configurations for Markdown
[language-server.ltex-ls.config]
ltex.dictionary = { "en-US" = ["builtin"], "en-GB" = ["builtin"] }

# Configurations for codebook
[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]


# === === === === Configuration for languages that also have Tailwind === === === ===
[language-server.tailwindcss-ls]
config = { userLanguages = { php = "html", "*.php" = "html" } } # This is done for the blade files on Laravel
