# Common LSP configurations

[[language]]

# TOML
# In the case of Artix Linux, the LSP is installed with a post hook
# For NixOS it is installed on the flake of the project
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

# YAML LSP Configurations
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"
