name: "Flake.lock Automatic Update"

on:
  schedule:
    - cron: "0 5 * * THU"

jobs:
  update-flake-on-hosts:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - name: Update Flake.lock of the Zephyrus host
        run: |
          cd "$GITHUB_WORKSPACE/nixos/hosts/zephyrus"
          nix flake update

          cd "$GITHUB_WORKSPACE/nixos/hosts/homelab/thinkcentre"
          nix flake update

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          cd "$GITHUB_WORKSPACE"

          git add nixos/hosts/zephyrus/flake.lock nixos/hosts/homelab/thinkcentre/flake.lock
          git commit -m "Updated flake.lock for the Thinkcentre and Zephyrus hosts" || echo "No update done to flake.lock files"
          git push
